version: '3.3'

services:
  db:
    image: mongo:4.0.11
    volumes:
      - db_data:/data/db
      - ./dbData:/tmp
    restart: "no"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    command: --sslMode requireSSL --sslPEMKeyFile /tmp/mongodb.pem

volumes:
  db_data:
